export const PATH = {
    login: "/login",
    register: "/register",
    accountInfo: "/account/info",
    accountDetail: "/account/detail",
    paymentPassword: "/account/paymentpassword",
    memberCard: "/account/memberCard",
    prizePoint: "/account/prizePoint",
    giftCard: "/account/giftCard",
    voucher: "/account/voucher",
    coupon: "/account/coupon",
    transactionHistory: "/account/transactionHistory",
    notFound: "/notfound",
    nowShowing: "/movies/nowShowing",
    comingSoon: "/movies/comingSoon",
    movieDetail: "/:tenPhim",
    cinemas: "/cinemas",
    booking: "/booking/:id",
    payment: "/payment/:id",
}; 